apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-web
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-web
  template:
    metadata:
      labels:
        app: airflow-web
    spec:
      containers:
        - name: airflow-web
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          ports:
            - containerPort: {{ .Values.airflow.web.port }}
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: {{ .Values.airflow.config.AIRFLOW__CORE__EXECUTOR }}
            - name: AIRFLOW__CORE__FERNET_KEY
              value: {{ .Values.airflow.config.AIRFLOW__CORE__FERNET_KEY }}
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: {{ .Values.airflow.config.AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION }}
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: {{ .Values.airflow.config.AIRFLOW__CORE__LOAD_EXAMPLES }}
