apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  namespace: airflow
spec:
  type: ClusterIP
  selector:
    app: airflow-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.airflow.web.port }}
