apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-operator
  namespace: default
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://airflow.apache.org/helm-charts
    targetRevision: HEAD
    helm:
      chart: airflow
      values: |
        ---
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
