apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  root-username: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
