apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: default
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessModes[0] }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
