apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
  selector:
    app: mongodb
