{{- if .Values.kafka.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ingress
  namespace: default
  annotations:
    {{- range $key, $value := .Values.kafka.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.kafka.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: kafka
                port:
                  number: {{ $.Values.kafka.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.kafka.ingress.tls }}
  tls:
    {{- range .Values.kafka.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
