apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: {{ .Values.elasticsearch.service.port }}
  selector:
    app: elasticsearch
