apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.port }}
  selector:
    app: kibana
