mongodb:
  image:
    repository: mongo
    tag: 4.4.6
  service:
    type: ClusterIP
    port: 27017
  auth:
    enabled: true
    rootUsername: root
    rootPassword: rootpassword
    database: admin
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: mongodb.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

resources: {}

config: {}
