# Default values for Kafka Helm chart

kafka:
  image:
    repository: bitnami/kafka
    tag: 2.8.0
  service:
    type: ClusterIP
    port: 9092

  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: kafka.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
