elasticsearch:
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 7.14.0
  service:
    type: ClusterIP
    port: 9200

  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: elasticsearch.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
