apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
  namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-operator
  namespace: default
spec:
  destination:
    namespace: elasticsearch
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: <your-elasticsearch-chart-repository-url>
    targetRevision: HEAD
    helm:
      chart: elasticsearch
      values: |
        ---
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
