airflow:
  image:
    repository: apache/airflow
    tag: 2.0.0
  executor: CeleryExecutor
  config:
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
    AIRFLOW__CORE__LOAD_EXAMPLES: "true"
  defaultAirflowTag: 2.0.0
  web:
    port: 8080

  postgresql:
    enabled: true
    postgresqlUsername: airflow
    postgresqlPassword: airflow
    postgresqlDatabase: airflow

  redis:
    enabled: true
    usePassword: false

  ingress:
    enabled: true
    annotations: {}
    hosts:
      - host: airflow.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: [] 

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
