apiVersion: v1
kind: Namespace
metadata:
  name: kibana
  namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana-operator
  namespace: default
spec:
  destination:
    namespace: kibana
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts
    targetRevision: Main
    helm:
      chart: kibana
      values: |
        ---
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
